version: '0.1'

services:
  backend:
    build: ./backend
    container_name: 'mobile-info-backend'
    ports:
      - "8080:8080"
    networks:
      - mobile-info-pro
    restart: unless-stopped

  content:
    build: ./content-generation
    container_name: 'mobile-info-content'
    ports:
      - "8000:8000"
    networks:
      - mobile-info-pro
    restart: unless-stopped

networks:
  mobile-info-pro:
    driver: bridge
