import dotenv from 'dotenv';
dotenv.config()
const brands = [
    {
        "id": 1,
        "brandName": "Apple",
        "globalStanding": "Global Leader (~21%)",
        "primaryMarket": "Global",
        "knownFor": "Premium iPhones, iOS ecosystem.",
        "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRduZVNLg_kNGvgZhtdv15W3OLpOKwMUPlEp-PD-yQXHA&s=10",
        "alt": "Logo of Apple, a Global Leader (~21%) smartphone brand.",
        "slug": "apple",
        "metaTitle": "Apple Smartphones | Global Leader (~21%) Mobile Brand Profile",
        "metaDescription": "Explore the Apple smartphone brand. Ranked as Global Leader (~21%), they dominate the Global market and are known for Premium iPhones, iOS ecosystem.",
        "focusKeyword": "Apple smartphones",
        "keywords": "Apple, Apple smartphones, Global mobile phones, Global Leader (~21%) brand, Premium iPhones"
    },
    {
        "id": 2,
        "brandName": "Samsung",
        "globalStanding": "Global Leader (~21%)",
        "primaryMarket": "Global",
        "knownFor": "High diversity (S-series, Foldables, A-series).",
        "img": "/images/samsung.png",
        "alt": "Logo of Samsung, a Global Leader (~21%) smartphone brand.",
        "slug": "samsung",
        "metaTitle": "Samsung Smartphones | Global Leader (~21%) Mobile Brand Profile",
        "metaDescription": "Explore the Samsung smartphone brand. Ranked as Global Leader (~21%), they dominate the Global market and are known for High diversity (S-series, Foldables, A-series).",
        "focusKeyword": "Samsung smartphones",
        "keywords": "Samsung, Samsung smartphones, Global mobile phones, Global Leader (~21%) brand, High diversity (S-series"
    },
    {
        "id": 3,
        "brandName": "Xiaomi",
        "globalStanding": "Top Tier (~11.5%)",
        "primaryMarket": "Asia, Europe",
        "knownFor": "High price-to-performance ratio.",
        "img": "/images/xiaomi.png",
        "alt": "Logo of Xiaomi, a Top Tier (~11.5%) smartphone brand.",
        "slug": "xiaomi",
        "metaTitle": "Xiaomi Smartphones | Top Tier (~11.5%) Mobile Brand Profile",
        "metaDescription": "Explore the Xiaomi smartphone brand. Ranked as Top Tier (~11.5%), they dominate the Asia, Europe market and are known for High price-to-performance ratio.",
        "focusKeyword": "Xiaomi smartphones",
        "keywords": "Xiaomi, Xiaomi smartphones, Asia, Europe mobile phones, Top Tier (~11.5%) brand, High price-to-performance ratio."
    },
    {
        "id": 4,
        "brandName": "OPPO",
        "globalStanding": "Top Tier (~10.5%)",
        "primaryMarket": "Asia, Europe",
        "knownFor": "VOOC fast-charging, premium mid-rangers.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=OPPO&size=150",
        "alt": "Logo of OPPO, a Top Tier (~10.5%) smartphone brand.",
        "slug": "oppo",
        "metaTitle": "OPPO Smartphones | Top Tier (~10.5%) Mobile Brand Profile",
        "metaDescription": "Explore the OPPO smartphone brand. Ranked as Top Tier (~10.5%), they dominate the Asia, Europe market and are known for VOOC fast-charging, premium mid-rangers.",
        "focusKeyword": "OPPO smartphones",
        "keywords": "OPPO, OPPO smartphones, Asia, Europe mobile phones, Top Tier (~10.5%) brand, VOOC fast-charging"
    },
    {
        "id": 5,
        "brandName": "Vivo",
        "globalStanding": "Top Tier (~7.5%)",
        "primaryMarket": "Asia",
        "knownFor": "Gimbal camera stabilization, heavy sports marketing.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Vivo&size=150",
        "alt": "Logo of Vivo, a Top Tier (~7.5%) smartphone brand.",
        "slug": "vivo",
        "metaTitle": "Vivo Smartphones | Top Tier (~7.5%) Mobile Brand Profile",
        "metaDescription": "Explore the Vivo smartphone brand. Ranked as Top Tier (~7.5%), they dominate the Asia market and are known for Gimbal camera stabilization, heavy sports marketing.",
        "focusKeyword": "Vivo smartphones",
        "keywords": "Vivo, Vivo smartphones, Asia mobile phones, Top Tier (~7.5%) brand, Gimbal camera stabilization"
    },
    {
        "id": 6,
        "brandName": "Redmi",
        "globalStanding": "Major Sub-brand (Xiaomi)",
        "primaryMarket": "Global",
        "knownFor": "Highly popular budget and mid-tier \"value\" devices.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Redmi&size=150",
        "alt": "Logo of Redmi, a Major Sub-brand (Xiaomi) smartphone brand.",
        "slug": "redmi",
        "metaTitle": "Redmi Smartphones | Major Sub-brand (Xiaomi) Mobile Brand Profile",
        "metaDescription": "Explore the Redmi smartphone brand. Ranked as Major Sub-brand (Xiaomi), they dominate the Global market and are known for Highly popular budget and mid-tier \"value\" devices.",
        "focusKeyword": "Redmi smartphones",
        "keywords": "Redmi, Redmi smartphones, Global mobile phones, Major Sub-brand (Xiaomi) brand, Highly popular budget and mid-tier \"value\" devices."
    },
    {
        "id": 7,
        "brandName": "Realme",
        "globalStanding": "Major Sub-brand (Oppo)",
        "primaryMarket": "South Asia, Europe",
        "knownFor": "Aggressive pricing for youth.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Realme&size=150",
        "alt": "Logo of Realme, a Major Sub-brand (Oppo) smartphone brand.",
        "slug": "realme",
        "metaTitle": "Realme Smartphones | Major Sub-brand (Oppo) Mobile Brand Profile",
        "metaDescription": "Explore the Realme smartphone brand. Ranked as Major Sub-brand (Oppo), they dominate the South Asia, Europe market and are known for Aggressive pricing for youth.",
        "focusKeyword": "Realme smartphones",
        "keywords": "Realme, Realme smartphones, South Asia, Europe mobile phones, Major Sub-brand (Oppo) brand, Aggressive pricing for youth."
    },
    {
        "id": 8,
        "brandName": "Motorola",
        "globalStanding": "Major Challenger (~2-4%)",
        "primaryMarket": "Americas, Europe",
        "knownFor": "Clean software, dominant in US budget tier.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Motorola&size=150",
        "alt": "Logo of Motorola, a Major Challenger (~2-4%) smartphone brand.",
        "slug": "motorola",
        "metaTitle": "Motorola Smartphones | Major Challenger (~2-4%) Mobile Brand Profile",
        "metaDescription": "Explore the Motorola smartphone brand. Ranked as Major Challenger (~2-4%), they dominate the Americas, Europe market and are known for Clean software, dominant in US budget tier.",
        "focusKeyword": "Motorola smartphones",
        "keywords": "Motorola, Motorola smartphones, Americas, Europe mobile phones, Major Challenger (~2-4%) brand, Clean software"
    },
    {
        "id": 9,
        "brandName": "Huawei",
        "globalStanding": "Major Challenger (~2-4%)",
        "primaryMarket": "China",
        "knownFor": "High-end camera engineering, HarmonyOS software.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Huawei&size=150",
        "alt": "Logo of Huawei, a Major Challenger (~2-4%) smartphone brand.",
        "slug": "huawei",
        "metaTitle": "Huawei Smartphones | Major Challenger (~2-4%) Mobile Brand Profile",
        "metaDescription": "Explore the Huawei smartphone brand. Ranked as Major Challenger (~2-4%), they dominate the China market and are known for High-end camera engineering, HarmonyOS software.",
        "focusKeyword": "Huawei smartphones",
        "keywords": "Huawei, Huawei smartphones, China mobile phones, Major Challenger (~2-4%) brand, High-end camera engineering"
    },
    {
        "id": 10,
        "brandName": "Honor",
        "globalStanding": "Major Challenger (~3-5%)",
        "primaryMarket": "Europe, Asia",
        "knownFor": "Premium hardware with full Google Play support.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Honor&size=150",
        "alt": "Logo of Honor, a Major Challenger (~3-5%) smartphone brand.",
        "slug": "honor",
        "metaTitle": "Honor Smartphones | Major Challenger (~3-5%) Mobile Brand Profile",
        "metaDescription": "Explore the Honor smartphone brand. Ranked as Major Challenger (~3-5%), they dominate the Europe, Asia market and are known for Premium hardware with full Google Play support.",
        "focusKeyword": "Honor smartphones",
        "keywords": "Honor, Honor smartphones, Europe, Asia mobile phones, Major Challenger (~3-5%) brand, Premium hardware with full Google Play support."
    },
    {
        "id": 11,
        "brandName": "Tecno",
        "globalStanding": "Regional Powerhouse",
        "primaryMarket": "Africa, South Asia",
        "knownFor": "Tailored camera features for local markets.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Tecno&size=150",
        "alt": "Logo of Tecno, a Regional Powerhouse smartphone brand.",
        "slug": "tecno",
        "metaTitle": "Tecno Smartphones | Regional Powerhouse Mobile Brand Profile",
        "metaDescription": "Explore the Tecno smartphone brand. Ranked as Regional Powerhouse, they dominate the Africa, South Asia market and are known for Tailored camera features for local markets.",
        "focusKeyword": "Tecno smartphones",
        "keywords": "Tecno, Tecno smartphones, Africa, South Asia mobile phones, Regional Powerhouse brand, Tailored camera features for local markets."
    },
    {
        "id": 12,
        "brandName": "Infinix",
        "globalStanding": "Regional Powerhouse",
        "primaryMarket": "Africa, Southeast Asia",
        "knownFor": "Value-focused sleek gaming phones.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Infinix&size=150",
        "alt": "Logo of Infinix, a Regional Powerhouse smartphone brand.",
        "slug": "infinix",
        "metaTitle": "Infinix Smartphones | Regional Powerhouse Mobile Brand Profile",
        "metaDescription": "Explore the Infinix smartphone brand. Ranked as Regional Powerhouse, they dominate the Africa, Southeast Asia market and are known for Value-focused sleek gaming phones.",
        "focusKeyword": "Infinix smartphones",
        "keywords": "Infinix, Infinix smartphones, Africa, Southeast Asia mobile phones, Regional Powerhouse brand, Value-focused sleek gaming phones."
    },
    {
        "id": 13,
        "brandName": "Google (Pixel)",
        "globalStanding": "High-Growth Challenger",
        "primaryMarket": "US, Japan, Western Europe",
        "knownFor": "Flagship camera AI features.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Google(Pixel)&size=150",
        "alt": "Logo of Google (Pixel), a High-Growth Challenger smartphone brand.",
        "slug": "google-pixel",
        "metaTitle": "Google (Pixel) Smartphones | High-Growth Challenger Mobile Brand Profile",
        "metaDescription": "Explore the Google (Pixel) smartphone brand. Ranked as High-Growth Challenger, they dominate the US, Japan, Western Europe market and are known for Flagship camera AI features.",
        "focusKeyword": "Google (Pixel) smartphones",
        "keywords": "Google (Pixel), Google (Pixel) smartphones, US, Japan, Western Europe mobile phones, High-Growth Challenger brand, Flagship camera AI features."
    },
    {
        "id": 14,
        "brandName": "OnePlus",
        "globalStanding": "Premium Sub-brand (Oppo)",
        "primaryMarket": "Global",
        "knownFor": "Fast performance software, alert slider hardware.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=OnePlus&size=150",
        "alt": "Logo of OnePlus, a Premium Sub-brand (Oppo) smartphone brand.",
        "slug": "oneplus",
        "metaTitle": "OnePlus Smartphones | Premium Sub-brand (Oppo) Mobile Brand Profile",
        "metaDescription": "Explore the OnePlus smartphone brand. Ranked as Premium Sub-brand (Oppo), they dominate the Global market and are known for Fast performance software, alert slider hardware.",
        "focusKeyword": "OnePlus smartphones",
        "keywords": "OnePlus, OnePlus smartphones, Global mobile phones, Premium Sub-brand (Oppo) brand, Fast performance software"
    },
    {
        "id": 15,
        "brandName": "Poco",
        "globalStanding": "Sub-brand (Xiaomi)",
        "primaryMarket": "India, Europe",
        "knownFor": "Maximum processing power for lowest cost.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Poco&size=150",
        "alt": "Logo of Poco, a Sub-brand (Xiaomi) smartphone brand.",
        "slug": "poco",
        "metaTitle": "Poco Smartphones | Sub-brand (Xiaomi) Mobile Brand Profile",
        "metaDescription": "Explore the Poco smartphone brand. Ranked as Sub-brand (Xiaomi), they dominate the India, Europe market and are known for Maximum processing power for lowest cost.",
        "focusKeyword": "Poco smartphones",
        "keywords": "Poco, Poco smartphones, India, Europe mobile phones, Sub-brand (Xiaomi) brand, Maximum processing power for lowest cost."
    },
    {
        "id": 16,
        "brandName": "iQOO",
        "globalStanding": "Gaming Sub-brand (Vivo)",
        "primaryMarket": "China, India",
        "knownFor": "Performance and liquid-cooled gaming phones.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=iQOO&size=150",
        "alt": "Logo of iQOO, a Gaming Sub-brand (Vivo) smartphone brand.",
        "slug": "iqoo",
        "metaTitle": "iQOO Smartphones | Gaming Sub-brand (Vivo) Mobile Brand Profile",
        "metaDescription": "Explore the iQOO smartphone brand. Ranked as Gaming Sub-brand (Vivo), they dominate the China, India market and are known for Performance and liquid-cooled gaming phones.",
        "focusKeyword": "iQOO smartphones",
        "keywords": "iQOO, iQOO smartphones, China, India mobile phones, Gaming Sub-brand (Vivo) brand, Performance and liquid-cooled gaming phones."
    },
    {
        "id": 17,
        "brandName": "itel",
        "globalStanding": "Regional Powerhouse",
        "primaryMarket": "Africa, South Asia",
        "knownFor": "Ultra-budget entry-level smartphones.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=itel&size=150",
        "alt": "Logo of itel, a Regional Powerhouse smartphone brand.",
        "slug": "itel",
        "metaTitle": "itel Smartphones | Regional Powerhouse Mobile Brand Profile",
        "metaDescription": "Explore the itel smartphone brand. Ranked as Regional Powerhouse, they dominate the Africa, South Asia market and are known for Ultra-budget entry-level smartphones.",
        "focusKeyword": "itel smartphones",
        "keywords": "itel, itel smartphones, Africa, South Asia mobile phones, Regional Powerhouse brand, Ultra-budget entry-level smartphones."
    },
    {
        "id": 18,
        "brandName": "Sony (Xperia)",
        "globalStanding": "Niche Enthusiast",
        "primaryMarket": "Global",
        "knownFor": "Premium pro-camera features, 4K multimedia focus.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Sony(Xperia)&size=150",
        "alt": "Logo of Sony (Xperia), a Niche Enthusiast smartphone brand.",
        "slug": "sony-xperia",
        "metaTitle": "Sony (Xperia) Smartphones | Niche Enthusiast Mobile Brand Profile",
        "metaDescription": "Explore the Sony (Xperia) smartphone brand. Ranked as Niche Enthusiast, they dominate the Global market and are known for Premium pro-camera features, 4K multimedia focus.",
        "focusKeyword": "Sony (Xperia) smartphones",
        "keywords": "Sony (Xperia), Sony (Xperia) smartphones, Global mobile phones, Niche Enthusiast brand, Premium pro-camera features"
    },
    {
        "id": 19,
        "brandName": "Asus (ROG/Zenfone)",
        "globalStanding": "Niche Enthusiast",
        "primaryMarket": "Global",
        "knownFor": "Hardcore gaming features (ROG) or compact powerhouses.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Asus(ROG/Zenfone)&size=150",
        "alt": "Logo of Asus (ROG/Zenfone), a Niche Enthusiast smartphone brand.",
        "slug": "asus-rog-zenfone",
        "metaTitle": "Asus (ROG/Zenfone) Smartphones | Niche Enthusiast Mobile Brand Profile",
        "metaDescription": "Explore the Asus (ROG/Zenfone) smartphone brand. Ranked as Niche Enthusiast, they dominate the Global market and are known for Hardcore gaming features (ROG) or compact powerhouses.",
        "focusKeyword": "Asus (ROG/Zenfone) smartphones",
        "keywords": "Asus (ROG/Zenfone), Asus (ROG/Zenfone) smartphones, Global mobile phones, Niche Enthusiast brand, Hardcore gaming features (ROG) or compact powerhouses."
    },
    {
        "id": 20,
        "brandName": "Nothing",
        "globalStanding": "Niche Challenger",
        "primaryMarket": "UK, Europe, India",
        "knownFor": "Semi-transparent hardware designs, Glyph LEDs.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Nothing&size=150",
        "alt": "Logo of Nothing, a Niche Challenger smartphone brand.",
        "slug": "nothing",
        "metaTitle": "Nothing Smartphones | Niche Challenger Mobile Brand Profile",
        "metaDescription": "Explore the Nothing smartphone brand. Ranked as Niche Challenger, they dominate the UK, Europe, India market and are known for Semi-transparent hardware designs, Glyph LEDs.",
        "focusKeyword": "Nothing smartphones",
        "keywords": "Nothing, Nothing smartphones, UK, Europe, India mobile phones, Niche Challenger brand, Semi-transparent hardware designs"
    },
    {
        "id": 21,
        "brandName": "ZTE",
        "globalStanding": "Mid-Tier Player",
        "primaryMarket": "Global",
        "knownFor": "Networking hardware, hidden under-display selfie cameras.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=ZTE&size=150",
        "alt": "Logo of ZTE, a Mid-Tier Player smartphone brand.",
        "slug": "zte",
        "metaTitle": "ZTE Smartphones | Mid-Tier Player Mobile Brand Profile",
        "metaDescription": "Explore the ZTE smartphone brand. Ranked as Mid-Tier Player, they dominate the Global market and are known for Networking hardware, hidden under-display selfie cameras.",
        "focusKeyword": "ZTE smartphones",
        "keywords": "ZTE, ZTE smartphones, Global mobile phones, Mid-Tier Player brand, Networking hardware"
    },
    {
        "id": 22,
        "brandName": "Nubia / RedMagic",
        "globalStanding": "Sub-brand (ZTE)",
        "primaryMarket": "Global",
        "knownFor": "Professional gaming phones with internal physical cooling fans.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Nubia/RedMagic&size=150",
        "alt": "Logo of Nubia / RedMagic, a Sub-brand (ZTE) smartphone brand.",
        "slug": "nubia---redmagic",
        "metaTitle": "Nubia / RedMagic Smartphones | Sub-brand (ZTE) Mobile Brand Profile",
        "metaDescription": "Explore the Nubia / RedMagic smartphone brand. Ranked as Sub-brand (ZTE), they dominate the Global market and are known for Professional gaming phones with internal physical cooling fans.",
        "focusKeyword": "Nubia / RedMagic smartphones",
        "keywords": "Nubia / RedMagic, Nubia / RedMagic smartphones, Global mobile phones, Sub-brand (ZTE) brand, Professional gaming phones with internal physical cooling fans."
    },
    {
        "id": 23,
        "brandName": "HMD",
        "globalStanding": "Niche Challenger",
        "primaryMarket": "Europe, US",
        "knownFor": "Highly repairable phones, successor to modern Nokia.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=HMD&size=150",
        "alt": "Logo of HMD, a Niche Challenger smartphone brand.",
        "slug": "hmd",
        "metaTitle": "HMD Smartphones | Niche Challenger Mobile Brand Profile",
        "metaDescription": "Explore the HMD smartphone brand. Ranked as Niche Challenger, they dominate the Europe, US market and are known for Highly repairable phones, successor to modern Nokia.",
        "focusKeyword": "HMD smartphones",
        "keywords": "HMD, HMD smartphones, Europe, US mobile phones, Niche Challenger brand, Highly repairable phones"
    },
    {
        "id": 24,
        "brandName": "Nokia",
        "globalStanding": "Legacy Brand (by HMD)",
        "primaryMarket": "Global",
        "knownFor": "Classic feature phones and simple, reliable budget devices.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Nokia&size=150",
        "alt": "Logo of Nokia, a Legacy Brand (by HMD) smartphone brand.",
        "slug": "nokia",
        "metaTitle": "Nokia Smartphones | Legacy Brand (by HMD) Mobile Brand Profile",
        "metaDescription": "Explore the Nokia smartphone brand. Ranked as Legacy Brand (by HMD), they dominate the Global market and are known for Classic feature phones and simple, reliable budget devices.",
        "focusKeyword": "Nokia smartphones",
        "keywords": "Nokia, Nokia smartphones, Global mobile phones, Legacy Brand (by HMD) brand, Classic feature phones and simple"
    },
    {
        "id": 25,
        "brandName": "Lava",
        "globalStanding": "Domestic Giant",
        "primaryMarket": "India",
        "knownFor": "Heavy domestic manufacturing, localized affordable devices.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Lava&size=150",
        "alt": "Logo of Lava, a Domestic Giant smartphone brand.",
        "slug": "lava",
        "metaTitle": "Lava Smartphones | Domestic Giant Mobile Brand Profile",
        "metaDescription": "Explore the Lava smartphone brand. Ranked as Domestic Giant, they dominate the India market and are known for Heavy domestic manufacturing, localized affordable devices.",
        "focusKeyword": "Lava smartphones",
        "keywords": "Lava, Lava smartphones, India mobile phones, Domestic Giant brand, Heavy domestic manufacturing"
    },
    {
        "id": 26,
        "brandName": "Sharp (Aquos)",
        "globalStanding": "Domestic Leader",
        "primaryMarket": "Japan",
        "knownFor": "Stunning custom IGZO screens, large camera sensors.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Sharp(Aquos)&size=150",
        "alt": "Logo of Sharp (Aquos), a Domestic Leader smartphone brand.",
        "slug": "sharp-aquos",
        "metaTitle": "Sharp (Aquos) Smartphones | Domestic Leader Mobile Brand Profile",
        "metaDescription": "Explore the Sharp (Aquos) smartphone brand. Ranked as Domestic Leader, they dominate the Japan market and are known for Stunning custom IGZO screens, large camera sensors.",
        "focusKeyword": "Sharp (Aquos) smartphones",
        "keywords": "Sharp (Aquos), Sharp (Aquos) smartphones, Japan mobile phones, Domestic Leader brand, Stunning custom IGZO screens"
    },
    {
        "id": 27,
        "brandName": "TCL",
        "globalStanding": "Mid-Tier Player",
        "primaryMarket": "US, Europe",
        "knownFor": "Budget devices with custom \"NXTPAPER\" displays.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=TCL&size=150",
        "alt": "Logo of TCL, a Mid-Tier Player smartphone brand.",
        "slug": "tcl",
        "metaTitle": "TCL Smartphones | Mid-Tier Player Mobile Brand Profile",
        "metaDescription": "Explore the TCL smartphone brand. Ranked as Mid-Tier Player, they dominate the US, Europe market and are known for Budget devices with custom \"NXTPAPER\" displays.",
        "focusKeyword": "TCL smartphones",
        "keywords": "TCL, TCL smartphones, US, Europe mobile phones, Mid-Tier Player brand, Budget devices with custom \"NXTPAPER\" displays."
    },
    {
        "id": 28,
        "brandName": "Blackview",
        "globalStanding": "Niche Specialist",
        "primaryMarket": "Global",
        "knownFor": "Highly popular rugged outdoor phones with heavy protection.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Blackview&size=150",
        "alt": "Logo of Blackview, a Niche Specialist smartphone brand.",
        "slug": "blackview",
        "metaTitle": "Blackview Smartphones | Niche Specialist Mobile Brand Profile",
        "metaDescription": "Explore the Blackview smartphone brand. Ranked as Niche Specialist, they dominate the Global market and are known for Highly popular rugged outdoor phones with heavy protection.",
        "focusKeyword": "Blackview smartphones",
        "keywords": "Blackview, Blackview smartphones, Global mobile phones, Niche Specialist brand, Highly popular rugged outdoor phones with heavy protection."
    },
    {
        "id": 29,
        "brandName": "Meizu",
        "globalStanding": "Automotive-Infused",
        "primaryMarket": "China",
        "knownFor": "Clean software UI, deeply tied to Geely smart electric cars.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Meizu&size=150",
        "alt": "Logo of Meizu, a Automotive-Infused smartphone brand.",
        "slug": "meizu",
        "metaTitle": "Meizu Smartphones | Automotive-Infused Mobile Brand Profile",
        "metaDescription": "Explore the Meizu smartphone brand. Ranked as Automotive-Infused, they dominate the China market and are known for Clean software UI, deeply tied to Geely smart electric cars.",
        "focusKeyword": "Meizu smartphones",
        "keywords": "Meizu, Meizu smartphones, China mobile phones, Automotive-Infused brand, Clean software UI"
    },
    {
        "id": 30,
        "brandName": "Micromax",
        "globalStanding": "Domestic Brand",
        "primaryMarket": "India",
        "knownFor": "Localized budget options attempting occasional comebacks.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Micromax&size=150",
        "alt": "Logo of Micromax, a Domestic Brand smartphone brand.",
        "slug": "micromax",
        "metaTitle": "Micromax Smartphones | Domestic Brand Mobile Brand Profile",
        "metaDescription": "Explore the Micromax smartphone brand. Ranked as Domestic Brand, they dominate the India market and are known for Localized budget options attempting occasional comebacks.",
        "focusKeyword": "Micromax smartphones",
        "keywords": "Micromax, Micromax smartphones, India mobile phones, Domestic Brand brand, Localized budget options attempting occasional comebacks."
    },
    {
        "id": 31,
        "brandName": "Ulefone",
        "globalStanding": "Niche Specialist",
        "primaryMarket": "Global",
        "knownFor": "Heavy-duty rugged smartphones with endoscope options.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Ulefone&size=150",
        "alt": "Logo of Ulefone, a Niche Specialist smartphone brand.",
        "slug": "ulefone",
        "metaTitle": "Ulefone Smartphones | Niche Specialist Mobile Brand Profile",
        "metaDescription": "Explore the Ulefone smartphone brand. Ranked as Niche Specialist, they dominate the Global market and are known for Heavy-duty rugged smartphones with endoscope options.",
        "focusKeyword": "Ulefone smartphones",
        "keywords": "Ulefone, Ulefone smartphones, Global mobile phones, Niche Specialist brand, Heavy-duty rugged smartphones with endoscope options."
    },
    {
        "id": 32,
        "brandName": "Doogee",
        "globalStanding": "Niche Specialist",
        "primaryMarket": "Global",
        "knownFor": "Ultra-durable rugged options with massive physical speaker builds.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Doogee&size=150",
        "alt": "Logo of Doogee, a Niche Specialist smartphone brand.",
        "slug": "doogee",
        "metaTitle": "Doogee Smartphones | Niche Specialist Mobile Brand Profile",
        "metaDescription": "Explore the Doogee smartphone brand. Ranked as Niche Specialist, they dominate the Global market and are known for Ultra-durable rugged options with massive physical speaker builds.",
        "focusKeyword": "Doogee smartphones",
        "keywords": "Doogee, Doogee smartphones, Global mobile phones, Niche Specialist brand, Ultra-durable rugged options with massive physical speaker builds."
    },
    {
        "id": 33,
        "brandName": "Oukitel",
        "globalStanding": "Niche Specialist",
        "primaryMarket": "Global",
        "knownFor": "Known for thick, unbreakable phones with massive batteries.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Oukitel&size=150",
        "alt": "Logo of Oukitel, a Niche Specialist smartphone brand.",
        "slug": "oukitel",
        "metaTitle": "Oukitel Smartphones | Niche Specialist Mobile Brand Profile",
        "metaDescription": "Explore the Oukitel smartphone brand. Ranked as Niche Specialist, they dominate the Global market and are known for Known for thick, unbreakable phones with massive batteries.",
        "focusKeyword": "Oukitel smartphones",
        "keywords": "Oukitel, Oukitel smartphones, Global mobile phones, Niche Specialist brand, Known for thick"
    },
    {
        "id": 34,
        "brandName": "Fairphone",
        "globalStanding": "Eco-Conscious Niche",
        "primaryMarket": "Europe",
        "knownFor": "100% sustainable, conflict-free minerals, DIY repairable.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Fairphone&size=150",
        "alt": "Logo of Fairphone, a Eco-Conscious Niche smartphone brand.",
        "slug": "fairphone",
        "metaTitle": "Fairphone Smartphones | Eco-Conscious Niche Mobile Brand Profile",
        "metaDescription": "Explore the Fairphone smartphone brand. Ranked as Eco-Conscious Niche, they dominate the Europe market and are known for 100% sustainable, conflict-free minerals, DIY repairable.",
        "focusKeyword": "Fairphone smartphones",
        "keywords": "Fairphone, Fairphone smartphones, Europe mobile phones, Eco-Conscious Niche brand, 100% sustainable"
    },
    {
        "id": 35,
        "brandName": "HTC",
        "globalStanding": "Legacy Niche",
        "primaryMarket": "Global",
        "knownFor": "Former market titan, now built as VIVE VR accessories.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=HTC&size=150",
        "alt": "Logo of HTC, a Legacy Niche smartphone brand.",
        "slug": "htc",
        "metaTitle": "HTC Smartphones | Legacy Niche Mobile Brand Profile",
        "metaDescription": "Explore the HTC smartphone brand. Ranked as Legacy Niche, they dominate the Global market and are known for Former market titan, now built as VIVE VR accessories.",
        "focusKeyword": "HTC smartphones",
        "keywords": "HTC, HTC smartphones, Global mobile phones, Legacy Niche brand, Former market titan"
    },
    {
        "id": 36,
        "brandName": "BLU Products",
        "globalStanding": "Regional Player",
        "primaryMarket": "North/Latin America",
        "knownFor": "Unlocked, highly affordable budget choices.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=BLUProducts&size=150",
        "alt": "Logo of BLU Products, a Regional Player smartphone brand.",
        "slug": "blu-products",
        "metaTitle": "BLU Products Smartphones | Regional Player Mobile Brand Profile",
        "metaDescription": "Explore the BLU Products smartphone brand. Ranked as Regional Player, they dominate the North/Latin America market and are known for Unlocked, highly affordable budget choices.",
        "focusKeyword": "BLU Products smartphones",
        "keywords": "BLU Products, BLU Products smartphones, North/Latin America mobile phones, Regional Player brand, Unlocked"
    },
    {
        "id": 37,
        "brandName": "Kyocera",
        "globalStanding": "Enterprise Specialist",
        "primaryMarket": "Japan, US",
        "knownFor": "Unbreakable medical and industrial-grade utility phones.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Kyocera&size=150",
        "alt": "Logo of Kyocera, a Enterprise Specialist smartphone brand.",
        "slug": "kyocera",
        "metaTitle": "Kyocera Smartphones | Enterprise Specialist Mobile Brand Profile",
        "metaDescription": "Explore the Kyocera smartphone brand. Ranked as Enterprise Specialist, they dominate the Japan, US market and are known for Unbreakable medical and industrial-grade utility phones.",
        "focusKeyword": "Kyocera smartphones",
        "keywords": "Kyocera, Kyocera smartphones, Japan, US mobile phones, Enterprise Specialist brand, Unbreakable medical and industrial-grade utility phones."
    },
    {
        "id": 38,
        "brandName": "Hisense",
        "globalStanding": "Electronics Offshoot",
        "primaryMarket": "China",
        "knownFor": "Specialized phones utilizing e-ink or high-battery designs.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Hisense&size=150",
        "alt": "Logo of Hisense, a Electronics Offshoot smartphone brand.",
        "slug": "hisense",
        "metaTitle": "Hisense Smartphones | Electronics Offshoot Mobile Brand Profile",
        "metaDescription": "Explore the Hisense smartphone brand. Ranked as Electronics Offshoot, they dominate the China market and are known for Specialized phones utilizing e-ink or high-battery designs.",
        "focusKeyword": "Hisense smartphones",
        "keywords": "Hisense, Hisense smartphones, China mobile phones, Electronics Offshoot brand, Specialized phones utilizing e-ink or high-battery designs."
    },
    {
        "id": 39,
        "brandName": "Umidigi",
        "globalStanding": "Budget E-commerce",
        "primaryMarket": "Global",
        "knownFor": "Accessible entry-tier phones sold widely on online markets.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Umidigi&size=150",
        "alt": "Logo of Umidigi, a Budget E-commerce smartphone brand.",
        "slug": "umidigi",
        "metaTitle": "Umidigi Smartphones | Budget E-commerce Mobile Brand Profile",
        "metaDescription": "Explore the Umidigi smartphone brand. Ranked as Budget E-commerce, they dominate the Global market and are known for Accessible entry-tier phones sold widely on online markets.",
        "focusKeyword": "Umidigi smartphones",
        "keywords": "Umidigi, Umidigi smartphones, Global mobile phones, Budget E-commerce brand, Accessible entry-tier phones sold widely on online markets."
    },
    {
        "id": 40,
        "brandName": "Cubot",
        "globalStanding": "Budget E-commerce",
        "primaryMarket": "Europe, South America",
        "knownFor": "Budget devices and mini android phones.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Cubot&size=150",
        "alt": "Logo of Cubot, a Budget E-commerce smartphone brand.",
        "slug": "cubot",
        "metaTitle": "Cubot Smartphones | Budget E-commerce Mobile Brand Profile",
        "metaDescription": "Explore the Cubot smartphone brand. Ranked as Budget E-commerce, they dominate the Europe, South America market and are known for Budget devices and mini android phones.",
        "focusKeyword": "Cubot smartphones",
        "keywords": "Cubot, Cubot smartphones, Europe, South America mobile phones, Budget E-commerce brand, Budget devices and mini android phones."
    },
    {
        "id": 41,
        "brandName": "Wiko",
        "globalStanding": "Regional Brand",
        "primaryMarket": "Europe",
        "knownFor": "Colorful, highly accessible low-cost entry phones.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Wiko&size=150",
        "alt": "Logo of Wiko, a Regional Brand smartphone brand.",
        "slug": "wiko",
        "metaTitle": "Wiko Smartphones | Regional Brand Mobile Brand Profile",
        "metaDescription": "Explore the Wiko smartphone brand. Ranked as Regional Brand, they dominate the Europe market and are known for Colorful, highly accessible low-cost entry phones.",
        "focusKeyword": "Wiko smartphones",
        "keywords": "Wiko, Wiko smartphones, Europe mobile phones, Regional Brand brand, Colorful"
    },
    {
        "id": 42,
        "brandName": "General Mobile",
        "globalStanding": "Regional Leader",
        "primaryMarket": "Turkey",
        "knownFor": "Local market leader heavily utilizing Android software.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=GeneralMobile&size=150",
        "alt": "Logo of General Mobile, a Regional Leader smartphone brand.",
        "slug": "general-mobile",
        "metaTitle": "General Mobile Smartphones | Regional Leader Mobile Brand Profile",
        "metaDescription": "Explore the General Mobile smartphone brand. Ranked as Regional Leader, they dominate the Turkey market and are known for Local market leader heavily utilizing Android software.",
        "focusKeyword": "General Mobile smartphones",
        "keywords": "General Mobile, General Mobile smartphones, Turkey mobile phones, Regional Leader brand, Local market leader heavily utilizing Android software."
    },
    {
        "id": 43,
        "brandName": "Lanix",
        "globalStanding": "Regional Leader",
        "primaryMarket": "Mexico",
        "knownFor": "Carrier-backed affordable prepaid devices.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Lanix&size=150",
        "alt": "Logo of Lanix, a Regional Leader smartphone brand.",
        "slug": "lanix",
        "metaTitle": "Lanix Smartphones | Regional Leader Mobile Brand Profile",
        "metaDescription": "Explore the Lanix smartphone brand. Ranked as Regional Leader, they dominate the Mexico market and are known for Carrier-backed affordable prepaid devices.",
        "focusKeyword": "Lanix smartphones",
        "keywords": "Lanix, Lanix smartphones, Mexico mobile phones, Regional Leader brand, Carrier-backed affordable prepaid devices."
    },
    {
        "id": 44,
        "brandName": "Positivo",
        "globalStanding": "Regional Leader",
        "primaryMarket": "Brazil",
        "knownFor": "Affordable technology tailored for South American consumers.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Positivo&size=150",
        "alt": "Logo of Positivo, a Regional Leader smartphone brand.",
        "slug": "positivo",
        "metaTitle": "Positivo Smartphones | Regional Leader Mobile Brand Profile",
        "metaDescription": "Explore the Positivo smartphone brand. Ranked as Regional Leader, they dominate the Brazil market and are known for Affordable technology tailored for South American consumers.",
        "focusKeyword": "Positivo smartphones",
        "keywords": "Positivo, Positivo smartphones, Brazil mobile phones, Regional Leader brand, Affordable technology tailored for South American consumers."
    },
    {
        "id": 45,
        "brandName": "Walton",
        "globalStanding": "Domestic Giant",
        "primaryMarket": "Bangladesh",
        "knownFor": "Heavy local tech manufacturing and distribution.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Walton&size=150",
        "alt": "Logo of Walton, a Domestic Giant smartphone brand.",
        "slug": "walton",
        "metaTitle": "Walton Smartphones | Domestic Giant Mobile Brand Profile",
        "metaDescription": "Explore the Walton smartphone brand. Ranked as Domestic Giant, they dominate the Bangladesh market and are known for Heavy local tech manufacturing and distribution.",
        "focusKeyword": "Walton smartphones",
        "keywords": "Walton, Walton smartphones, Bangladesh mobile phones, Domestic Giant brand, Heavy local tech manufacturing and distribution."
    },
    {
        "id": 46,
        "brandName": "Mobicel",
        "globalStanding": "Regional Leader",
        "primaryMarket": "South Africa",
        "knownFor": "Budget smartphones lowering the barrier to data entry.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Mobicel&size=150",
        "alt": "Logo of Mobicel, a Regional Leader smartphone brand.",
        "slug": "mobicel",
        "metaTitle": "Mobicel Smartphones | Regional Leader Mobile Brand Profile",
        "metaDescription": "Explore the Mobicel smartphone brand. Ranked as Regional Leader, they dominate the South Africa market and are known for Budget smartphones lowering the barrier to data entry.",
        "focusKeyword": "Mobicel smartphones",
        "keywords": "Mobicel, Mobicel smartphones, South Africa mobile phones, Regional Leader brand, Budget smartphones lowering the barrier to data entry."
    },
    {
        "id": 47,
        "brandName": "Symphony",
        "globalStanding": "Domestic Leader",
        "primaryMarket": "Bangladesh",
        "knownFor": "Dominates local entry-level market volume.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Symphony&size=150",
        "alt": "Logo of Symphony, a Domestic Leader smartphone brand.",
        "slug": "symphony",
        "metaTitle": "Symphony Smartphones | Domestic Leader Mobile Brand Profile",
        "metaDescription": "Explore the Symphony smartphone brand. Ranked as Domestic Leader, they dominate the Bangladesh market and are known for Dominates local entry-level market volume.",
        "focusKeyword": "Symphony smartphones",
        "keywords": "Symphony, Symphony smartphones, Bangladesh mobile phones, Domestic Leader brand, Dominates local entry-level market volume."
    },
    {
        "id": 48,
        "brandName": "Cherry Mobile",
        "globalStanding": "Regional Leader",
        "primaryMarket": "Philippines",
        "knownFor": "Value-focused devices built for the domestic market.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=CherryMobile&size=150",
        "alt": "Logo of Cherry Mobile, a Regional Leader smartphone brand.",
        "slug": "cherry-mobile",
        "metaTitle": "Cherry Mobile Smartphones | Regional Leader Mobile Brand Profile",
        "metaDescription": "Explore the Cherry Mobile smartphone brand. Ranked as Regional Leader, they dominate the Philippines market and are known for Value-focused devices built for the domestic market.",
        "focusKeyword": "Cherry Mobile smartphones",
        "keywords": "Cherry Mobile, Cherry Mobile smartphones, Philippines mobile phones, Regional Leader brand, Value-focused devices built for the domestic market."
    },
    {
        "id": 49,
        "brandName": "Bphone",
        "globalStanding": "Niche Domestic",
        "primaryMarket": "Vietnam",
        "knownFor": "High-security domestic engineering and premium styling.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Bphone&size=150",
        "alt": "Logo of Bphone, a Niche Domestic smartphone brand.",
        "slug": "bphone",
        "metaTitle": "Bphone Smartphones | Niche Domestic Mobile Brand Profile",
        "metaDescription": "Explore the Bphone smartphone brand. Ranked as Niche Domestic, they dominate the Vietnam market and are known for High-security domestic engineering and premium styling.",
        "focusKeyword": "Bphone smartphones",
        "keywords": "Bphone, Bphone smartphones, Vietnam mobile phones, Niche Domestic brand, High-security domestic engineering and premium styling."
    },
    {
        "id": 50,
        "brandName": "Librem (Purism)",
        "globalStanding": "Security Niche",
        "primaryMarket": "Global",
        "knownFor": "Privacy-first Linux phones with physical hardware kill-switches.",
        "img": "https://api.dicebear.com/7.0/identicon/png?seed=Librem(Purism)&size=150",
        "alt": "Logo of Librem (Purism), a Security Niche smartphone brand.",
        "slug": "librem-purism",
        "metaTitle": "Librem (Purism) Smartphones | Security Niche Mobile Brand Profile",
        "metaDescription": "Explore the Librem (Purism) smartphone brand. Ranked as Security Niche, they dominate the Global market and are known for Privacy-first Linux phones with physical hardware kill-switches.",
        "focusKeyword": "Librem (Purism) smartphones",
        "keywords": "Librem (Purism), Librem (Purism) smartphones, Global mobile phones, Security Niche brand, Privacy-first Linux phones with physical hardware kill-switches."
    }
]

for (let i = 0; i < brands.length; i++) {
    const { brandName, knownFor, globalStanding } = brands[i];

    try {
        const res = await fetch(`${process.env.BACKEND}/api/brand/create`, {
            method: 'POST',
            headers: {
                "Content-type": "application/json",
            },
            body: JSON.stringify({ name: brandName, knownFor, globalStanding }),
        })

    } catch (error) {
        console.log(error)
    }

}